### ISSUE TITLE
MetadataStore#addOrUpdateUser is open

### ISSUE THREAD

**Issue by 3esmit** [status-im/status-teller-network#206]
### Bug Report
Function allows access by anyone to anyone.

#### Summary
MetadataStore.sol function addOrUpdateUser(address _user, bytes _statusContactCode, string _location, string _username) is bad. _user parameter is open, so anyone can change anyone information. 

#### Suggested Fix
Functions need to consider msg.sender for defining the address of _user:

```
function addOrUpdateUser(bytes _statusContactCode, string _location, string _username) external {
address _user = msg.sender;
(...)
}
```

I see that this "open" is a feature to allow new buyers having their data being set by seller. To keep this capability, but safe, require a ethereum signed message containing the contract address and the parameters. The recovered address of the signature is set as _user.

```
function addOrUpdateUser(bytes _statusContactCode, string _location, string _username, bytes _signature) public {
address _user = recoverAddress(keccak256(address(this), _statusContactCode, _location, _username), _signature);
(...)
}
```

**Comment by arsenyjin** [comment]
https://github.com/status-im/status-teller-network/pull/228

**Comment by arsenyjin** [comment]
I guess we can close the issue because of the  https://github.com/status-im/status-teller-network/pull/314
